import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import _ from 'lodash';
import { Schema } from '../src/cmyj-1.9/schema/definition.js';
import { assetOwner, settlePrivateIncome } from '../src/cmyj-1.9/shared/finance.js';
let stored={stat_data:Schema.parse({经济:{分账启用:true,资产:{店铺:{归属:'皇家私人',月入:5,币种:'白银两'}},国家财政:{余额:{白银两:100}}},主角:{私库:{金银铜:{白银:50}}}})};let changed=0;
const ctx=vm.createContext({structuredClone,window:{},Mvu:{getMvuData:()=>structuredClone(stored),replaceMvuData:async v=>{stored={...v,stat_data:Schema.parse(v.stat_data)};}}});
const source=fs.readFileSync(new URL('../src/cmyj-1.9/variable-editor/index.js',import.meta.url),'utf8');
vm.runInContext(source.replace('  globalThis.CanmingVariableEditor =','  globalThis.testEditor = { state, setByPath, writeStatData, refreshData };\n  globalThis.CanmingVariableEditor ='),ctx);
const ed=ctx.testEditor;ed.refreshData();ed.state.onChanged=()=>changed++;
ed.setByPath(ed.state.data,['经济','资产','店铺','月入'],8);
ed.setByPath(ed.state.data,['经济','国家财政','余额','白银两'],110);
ed.setByPath(ed.state.data,['经济','国家财政','收支记录','收税'],{日期:'本月',类型:'收入',金额:10,币种:'白银两',说明:'税收'});
ed.setByPath(ed.state.data,['主角','私库','金银铜','白银'],47);
ed.setByPath(ed.state.data,['主角','私库','收支记录','购买'],{日期:'本月',类型:'支出',金额:3,币种:'白银两',说明:'购买'});
await ed.writeStatData();assert.equal(changed,1);ed.refreshData();assert.equal(ed.state.data.经济.资产.店铺.月入,8);assert.equal(ed.state.data.主角.私库.金银铜.白银,47);
const src=fs.readFileSync(new URL('../src/cmyj-1.9/statusbar/index.js',import.meta.url),'utf8');
const render=vm.createContext({statData:stored.stat_data,get:_.get,assetOwner,html:String,tag:x=>x,meta:(a,b)=>a+':'+b,card:(a,b)=>a+'\n'+b,renderMoneyViewSwitch:()=>'',recordList:(r,f)=>Object.entries(r).map(([k,v])=>f(k,v)).join('\n'),compactObject:()=>''});
vm.runInContext(src.slice(src.indexOf('function renderAccountLedger'),src.indexOf('function renderPublicAccount'))+src.slice(src.indexOf('function renderSeparatedMoney'),src.indexOf('function renderMoney()')),render);
const output=render.renderSeparatedMoney();for(const x of ['国有资产','皇室资产','8 白银两/月','已记收入:10','已记支出:3','税收','购买'])assert(output.includes(x),x);
for(const x of ['核准','待核','非收益','上次结算'])assert(!output.includes(x),x);
settlePrivateIncome(stored.stat_data,'next-month');assert.equal(stored.stat_data.主角.私库.金银铜.白银,55);assert.equal(stored.stat_data.经济.国家财政.余额.白银两,110);
console.log('PASS editor write/read through schema, callback refresh, both ledgers and balances rendered, monthly income without approval metadata');
