import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import { marketItems, marketCategories } from '../src/cmyj-1.9/shared/market.js';
import { settlePrivateIncome } from '../src/cmyj-1.9/shared/finance.js';
import { Schema } from '../src/cmyj-1.9/schema/definition.js';
const market={商品价格:{phone:{名称:'手机',分类:'数码',单位:'台',白银单价:3.676921,人民币参考价:3000,月库存:10,默认数量:1}},价格指数:{数码:100}};
assert.equal(marketItems([{id:'legacy'}],{} )[0].id,'legacy');
assert.equal(marketItems([],market)[0].basePrice,3.676921);
assert.deepEqual(marketCategories([],market),[['数码','数码']]);
const parsed=Schema.parse({经济:{大靖元等值白银:true,市场:market}});
assert.deepEqual(parsed.经济.市场.商品价格,Schema.parse(parsed).经济.市场.商品价格);
assert.equal(parsed.经济.市场.价格指数.数码,100);
const src=fs.readFileSync(new URL('../src/cmyj-1.9/statusbar/index.js',import.meta.url),'utf8');
const number=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const context=vm.createContext({number,clamp:(v,a,b)=>Math.max(a,Math.min(b,v)),roundMarketNumber:(v)=>Math.round(v*1e6)/1e6});
vm.runInContext(src.slice(src.indexOf('function getMarketItemPriceInSilver'),src.indexOf('function classifyCampType')),context);
const item=marketItems([],market)[0];
assert.equal(context.getMarketItemPriceInSilver(item,market,2),7.353842);
const quote=context.getMarketPaymentQuote(7.353842,'大靖元',market);
assert.equal(quote.key,'白银');assert.equal(quote.amount,7.353842);
assert.equal(context.getMarketItemPriceInSilver(item,{...market,价格指数:{数码:120}},1),4.412305);
const data={经济:{大靖元等值白银:true,资产:{股息:{月入:3,币种:'大靖元',归属:'皇家私人',收益核准:true,依据:'净分红'}}},主角:{私库:{金银铜:{白银:10}}}};
settlePrivateIncome(data,'month');assert.equal(data.主角.私库.金银铜.白银,13);assert.equal(data.主角.私库.其他货币.大靖元,undefined);
assert.equal(data.主角.私库.收支记录['月结-month-股息'].币种,'白银两');
console.log('PASS campaign catalog, legacy fallback, schema persistence, exact checkout, price index and 1:1 yuan settlement');
